/**
 * @bsvibe/demo/testing — Playwright suite library.
 *
 * Each product registers the same set of demo-smoke tests by calling
 * {@link runDemoSmokeSuite} from its e2e spec file:
 *
 * ```ts
 * // frontend/e2e/demo-smoke.spec.ts
 * import { runDemoSmokeSuite } from "@bsvibe/demo/testing";
 *
 * runDemoSmokeSuite({
 *   product: "BSGateway",
 *   baseUrl: process.env.DEMO_E2E_BASE_URL ?? "http://localhost:13301",
 *   apiUrl:  process.env.DEMO_E2E_API_URL  ?? "http://localhost:14500",
 * });
 * ```
 *
 * The suite is tagged ``@demo`` so prod e2e runs can grep it out:
 * ``pnpm test:e2e --grep-invert @demo`` for prod-only.
 *
 * Tests cover the four bug classes that surfaced in the initial demo
 * rollout — each one would have been caught pre-merge if this suite had
 * existed:
 *
 * 1. ``isDemoMode()`` returning false at runtime (LoginPage shows instead
 *    of DemoShell).
 * 2. Middleware redirecting unauthenticated requests to ``/login`` before
 *    the demo session bootstrap can run.
 * 3. ``/api/v1/demo/session`` 500ing because the seed inserts mismatch the
 *    table schema.
 * 4. Per-visitor tenant isolation broken (two browsers seeing the same
 *    tenant_id).
 */

import { expect, test, type Browser } from "@playwright/test";

export interface SmokeSuiteOptions {
  /** Display name for the test describe block (e.g. "BSGateway"). */
  product: string;
  /** Frontend URL — usually ``http://localhost:<frontend port>`` locally. */
  baseUrl: string;
  /** Backend URL — usually ``http://localhost:<backend port>`` locally. */
  apiUrl: string;
  /**
   * Optional regex matching paths that should be considered "the dashboard".
   * Defaults to ``/^(\/|\/(ko|en))?$/`` (root or locale-prefixed root). Override
   * for products that redirect to a sub-route on demo entry (e.g. ``/dashboard``).
   */
  dashboardPath?: RegExp;
  /**
   * Optional regex of paths that constitute "redirected to login" — fail signal.
   * Default: ``/login/i``.
   */
  loginPath?: RegExp;
  /**
   * Tenant isolation model for this product:
   * - ``"per-visitor"`` (default): each /demo/session call gets a unique
   *   tenant_id. The isolation test asserts two contexts get different ids.
   * - ``"shared"``: all visitors share a single demo tenant (used by
   *   read-mostly showcase products like BSupervisor and BSage). The
   *   isolation test inverts and asserts the same tenant_id is returned.
   */
  tenantModel?: "per-visitor" | "shared";
}

export function runDemoSmokeSuite(opts: SmokeSuiteOptions): void {
  const {
    product,
    baseUrl,
    apiUrl,
    loginPath = /\/login(\b|\/)/i,
    tenantModel = "per-visitor",
  } = opts;

  test.describe(`@demo ${product} smoke`, () => {
    test("POST /api/v1/demo/session returns 201 with tenant_id", async ({ request }) => {
      const resp = await request.post(`${apiUrl}/api/v1/demo/session`);
      expect(resp.status(), `status (body=${await resp.text()})`).toBe(201);
      const body = (await resp.json()) as {
        tenant_id?: string;
        token?: string;
        expires_in?: number;
      };
      expect(body.tenant_id).toMatch(/^[0-9a-f-]{36}$/);
      expect(body.token).toBeTruthy();
      expect(body.expires_in).toBeGreaterThan(0);
    });

    test("root URL renders DemoBanner, not LoginPage", async ({ page }) => {
      await page.goto(baseUrl);
      // The middleware-or-React-shell should NOT redirect us to /login.
      // Allow ~5s for client redirects to settle.
      await page.waitForLoadState("networkidle");
      expect(page.url(), "should not redirect to /login").not.toMatch(loginPath);

      // Demo banner is the canonical signal. Generated by @bsvibe/demo's
      // <DemoBanner>, copy starts with "Demo mode" / "데모 모드".
      const banner = page.getByText(/demo mode|데모 모드/i).first();
      await expect(banner, "DemoBanner should be visible on demo deployments").toBeVisible({
        timeout: 15_000,
      });
    });

    const isolationLabel =
      tenantModel === "shared"
        ? "two browser contexts share the same demo tenant_id"
        : "two browser contexts get isolated tenant_ids";
    test(isolationLabel, async ({ browser }: { browser: Browser }) => {
      const ctxA = await browser.newContext();
      const ctxB = await browser.newContext();
      try {
        const [a, b] = await Promise.all([
          ctxA.request.post(`${apiUrl}/api/v1/demo/session`),
          ctxB.request.post(`${apiUrl}/api/v1/demo/session`),
        ]);
        expect(a.status()).toBe(201);
        expect(b.status()).toBe(201);
        const bodyA = (await a.json()) as { tenant_id: string };
        const bodyB = (await b.json()) as { tenant_id: string };
        if (tenantModel === "shared") {
          expect(bodyA.tenant_id, "shared-tenant products must return one demo tenant for all visitors").toBe(
            bodyB.tenant_id,
          );
        } else {
          expect(bodyA.tenant_id).not.toBe(bodyB.tenant_id);
        }
      } finally {
        await ctxA.close();
        await ctxB.close();
      }
    });

    test("session cookie is set with HttpOnly + SameSite", async ({ request }) => {
      const resp = await request.post(`${apiUrl}/api/v1/demo/session`);
      const setCookie = resp.headers()["set-cookie"] ?? "";
      expect(setCookie, "Set-Cookie header missing on /demo/session").toContain(
        "bsvibe_demo_session=",
      );
      expect(setCookie.toLowerCase()).toContain("httponly");
      expect(setCookie.toLowerCase()).toContain("samesite");
    });
  });
}
